package render

import (
	"fmt"
	"strings"
	"time"

	"github.com/zvdy/stratum/internal/schema"
)

// GeneratedLinePrefix marks the single volatile (timestamp-bearing) line in a
// generated document. Tools that need to compare documents by content — e.g.
// the CLI's --check mode — strip the line with this prefix so the timestamp
// does not register as a difference.
const GeneratedLinePrefix = "_Generated by stratum on "

// Markdown renders a full schema document: header, table of contents, the
// Mermaid ERD, and per-table detail sections. now and srcPath are injected so
// output is deterministic and testable.
func Markdown(s *schema.Schema, srcPath string, now time.Time) string {
	var b strings.Builder

	b.WriteString("# Schema\n\n")
	b.WriteString(GeneratedLinePrefix)
	fmt.Fprintf(&b, "%s from `%s`._\n\n", now.UTC().Format(time.RFC3339), srcPath)

	keys := s.SortedTableKeys()

	// Table of contents.
	b.WriteString("## Tables\n\n")
	if len(keys) == 0 {
		b.WriteString("_No tables found._\n\n")
	} else {
		for _, key := range keys {
			name := entityName(s.Tables[key].Name)
			fmt.Fprintf(&b, "- [%s](#%s)\n", name, anchor(name))
		}
		b.WriteByte('\n')
	}

	// ERD.
	b.WriteString("## ERD\n\n")
	b.WriteString(Mermaid(s))
	b.WriteString("\n\n")

	// Per-table detail.
	for _, key := range keys {
		writeTableSection(&b, s.Tables[key])
	}

	return b.String()
}

func writeTableSection(b *strings.Builder, t *schema.Table) {
	name := entityName(t.Name)
	fmt.Fprintf(b, "## %s\n\n", name)

	// Columns.
	b.WriteString("### Columns\n\n")
	b.WriteString("| Name | Type | Nullable | Default | Constraints |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, c := range t.Columns {
		nullable := "yes"
		if c.NotNull {
			nullable = "no"
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s | %s |\n",
			c.Name, mdCode(c.Type), nullable, mdDefault(c.Default), constraintTags(t, c))
	}
	b.WriteByte('\n')

	// Indexes.
	if len(t.Indexes) > 0 {
		b.WriteString("### Indexes\n\n")
		b.WriteString("| Name | Columns | Unique |\n")
		b.WriteString("| --- | --- | --- |\n")
		for _, idx := range t.Indexes {
			unique := "no"
			if idx.Unique {
				unique = "yes"
			}
			fmt.Fprintf(b, "| %s | %s | %s |\n",
				orDash(idx.Name), strings.Join(idx.Columns, ", "), unique)
		}
		b.WriteByte('\n')
	}

	// Foreign keys.
	if len(t.FKs) > 0 {
		b.WriteString("### Foreign Keys\n\n")
		b.WriteString("| Name | Columns | References |\n")
		b.WriteString("| --- | --- | --- |\n")
		for _, fk := range t.FKs {
			ref := entityName(fk.RefTable)
			if len(fk.RefColumns) > 0 {
				ref += " (" + strings.Join(fk.RefColumns, ", ") + ")"
			}
			fmt.Fprintf(b, "| %s | %s | %s |\n",
				orDash(fk.Name), strings.Join(fk.Columns, ", "), ref)
		}
		b.WriteByte('\n')
	}

	// Checks (only those we could textualize).
	var checks []schema.Check
	for _, ck := range t.Checks {
		if ck.Expr != "" {
			checks = append(checks, ck)
		}
	}
	if len(checks) > 0 {
		b.WriteString("### Checks\n\n")
		for _, ck := range checks {
			if ck.Name != "" {
				fmt.Fprintf(b, "- **%s**: `%s`\n", ck.Name, ck.Expr)
			} else {
				fmt.Fprintf(b, "- `%s`\n", ck.Expr)
			}
		}
		b.WriteByte('\n')
	}
}

// constraintTags lists the constraint markers applicable to a column.
func constraintTags(t *schema.Table, c schema.Column) string {
	var tags []string
	if c.PrimaryKey {
		tags = append(tags, "PK")
	}
	if t.IsFKColumn(c.Name) {
		tags = append(tags, "FK")
	}
	for _, idx := range t.Indexes {
		if idx.Unique && len(idx.Columns) == 1 && idx.Columns[0] == c.Name {
			tags = append(tags, "unique")
			break // a column is "unique" once regardless of how many indexes enforce it
		}
	}
	if len(tags) == 0 {
		return ""
	}
	return strings.Join(tags, ", ")
}

// anchor mimics GitHub's heading-to-anchor slug for the TOC links.
func anchor(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == ' ', r == '-', r == '_':
			b.WriteByte('-')
		}
	}
	return b.String()
}

func mdCode(s string) string {
	if s == "" {
		return ""
	}
	return "`" + s + "`"
}

func mdDefault(s string) string {
	if s == "" {
		return ""
	}
	return "`" + s + "`"
}

func orDash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}
